version: '3.1'

services:
  parser_app:
    build: ./
    command: python3 parse_app/main.py
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=zxc
      - POSTGRES_PASSWORD=zxc
      - POSTGRES_DB=real_estate
    container_name: postgres_db
    ports:
      - 5432:5432

volumes:
  postgres_data: